services:
  postgres:
    image: postgres:18
    container_name: stc-postgres
    environment:
      POSTGRES_DB: stc-server
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stc-server
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/stc-server
      SEC_CERTIFICATE: ${SEC_CERTIFICATE}
      SEC_PRIVATE_KEY: ${SEC_PRIVATE_KEY}
      RUST_LOG: stc_server=info,tracing_actix_web=info,actix_web=warn
    ports:
      - "8080:8000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
